### ISSUE TITLE
Roadmap and basic features

### ISSUE THREAD

**Issue by adelhult** [adelhult/hypatia#1]
- [x] Expose a nicer API with a parse and eval function (or maybe just a eval that takes a &str)
- [x] Add scopes
- [x] Create a way of testing files in the samples dir
- [x] Add "update" keyword
- [x] Replace Number with Quantity
- [x] Disallow units and variable names to collide
- [x] Allow for omitting numeric values in unit expressions (i.e. `unit foo = 2 m *  kg`
- [x] Add a prelude
- [ ] Add `in` conversion operator
- [x] Add comparison operators
- [x] Add logical operators 
- [x] Add functions
- [ ] Fix lexical scope bug
- [ ] Add useful math functions `sin`, `cos` etc.
- [x] Integrate into a notebook editor on the web via a WASM build
- [ ] Perhaps a postfix application operator
- [x] Add unit prefixes (kilo, mega, etc.)
- [x] Add support for binary and hex literals as well as maybe bit manipulation operators (this might require a distinction between Real and Integer types)
